### ISSUE TITLE
EHN: Update class inventory manager with correct materials

### ISSUE THREAD

**Issue by iquelli** [TiagoFar78/PrisonEscape#16]

**Comment by iquelli** [comment]
Ainda temos como cada item vai ser representado no minecraft @TiagoFar78

**Comment by iquelli** [comment]
STICK - minecraft stick
    SEARCH - 
    HANDCUFS - 
    SPOON - 
    SHOVEL - 
    MATCHES - torches (suggestion)
    BOLTS -
    DUCTTAPE - 
    WIRE - redstone payder ?
    PLASTICPLATE - 
    OIL - 
    COFFEE - potion
    ENERGYDRINK - potion

**Comment by iquelli** [comment]
@TiagoFar78  dps se tiveres ideias comenta aí e acrescento

**Comment by TiagoFar78** [comment]
STICK - minecraft stick
SEARCH - compass ? I don't know yet because it seems to be better to use to represent radio
HANDCUFS - lead
SPOON - 
SHOVEL - 
MATCHES - torches (suggestion)
BOLTS - iron ?
DUCTTAPE - slime ?
WIRE - redstone powder ? I thinks it's nice.
PLASTICPLATE - 
OIL - flint and steel / coal / charcoal
COFFEE - speed potion 2
ENERGYDRINK - speed potion 2

About the spoons and plates I think we can ignore a little bit the original prison life game and use some minecraft items. This is what I suggest:
Plastic spoon -> wooden shovel
Metal spoon -> gold shovel
Plastic shovel -> iron shovel (maybe stone shovel because it is supposed to be undetected in metal detectors)
Metal spoon -> diamond shovel

**Comment by iquelli** [comment]
@TiagoFar78  updated it

**Comment by TiagoFar78** [comment]
Now that you mention bars I feel like it would perfecly match the HANDCUFFS item since it gives vibes of "behind bars". As for SEARCH item I think a spyglass should do the job.

**Comment by iquelli** [comment]
> Now that you mention bars I feel like it would perfecly match the HANDCUFFS item since it gives vibes of "behind bars". As for SEARCH item I think a spyglass should do the job.

Oke will update the materials according to the list
